# Dependencies(Build Settings)
markdown            : kramdown
gems                : ["jekyll-paginate"]

# Permalinks
permalink           : pretty
# there are many kinds of modes, including date, pretty, ordinal, none.
# mode date is the default value.
# know more from http://jekyllcn.com/docs/permalinks/

# Site Info
title               : BW's Landing Page
title-cn            : 發現．BW
keywords            : imprld01,imprld,BW's Landing Page
tagline             : A Site about Personal Pages.(A Landing Page)
description         : > # this means to ignore newlines until "url:"
  This is a personal landing page linking to my profile, blog, etc. Very welcome to my landing page!
  This site is owned by Bo-Wun! In this site, you can find more info about bo-wun,
  including experience, interests,etc. Bo-Wun a.k.a Brian. If you are interested, you can mail to me!
url                 : https://imprld01.github.io
# the base hostname & protocol for your site
baseurl             : 
# the subpath of your site

# Personal Info
author              : imprld01
name                : imprld01
email               : sbw2319@gmail.com

# Custom Vars
version             : 0.1.0
github_username     : imprld01
github_url          : https://github.com/imprld01
